# Build and push docker images to docker hub
name: Build and push docker images

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]

jobs:
  docker1:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push a test image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: solids4foam/sandbox:v1.0
          file: Dockerfile.sandbox

  docker2:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push a test image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: solids4foam/sandbox:v2.0
          file: Dockerfile.sandbox