# Check all links in markdown files
name: Linkcheck

on:
  push:
    paths:
    - '*.md'
    - '/documentation/*.md'
    - '/installation/*.md'
    - '/tutorials/*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: md-linkcheck
      uses: ocular-d/md-linkcheck-action@master